# Generated by Django 2.2.6 on 2019-10-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='contact_large_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_small_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
