# Generated by Django 2.2.6 on 2019-10-07 18:33

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('blog_post_title', models.CharField(help_text='Overwrites the default title', max_length=100)),
                ('blog_post_description', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('blog_post_content', wagtail.core.fields.RichTextField()),
                ('blog_post_image', models.ForeignKey(blank=True, null=True, on_delete='models.SET_NULL', related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
