# Generated by Django 2.2.6 on 2019-10-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_bloglistingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglistingpage',
            name='blog_listing_large_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingpage',
            name='blog_listing_small_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
