# Generated by Django 2.2.6 on 2019-10-07 21:10

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogauthor_blogauthorsorderable'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
