# Generated by Django 2.2.6 on 2019-10-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogauthor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
