# Generated by Django 2.2.6 on 2019-10-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogauthor_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='description_should_appear_at_top_of_blog_post',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
