# Generated by Django 2.2.6 on 2019-10-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_description_should_appear_at_top_of_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='authored_by_large_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='authored_by_small_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
